"""Unique

Revision ID: 18b1955f4dd0
Revises: 3be0d4d09c09
Create Date: 2021-12-22 21:56:52.654042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18b1955f4dd0'
down_revision = '3be0d4d09c09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_roleuser_login', table_name='roleuser')
    op.create_index(op.f('ix_roleuser_login'), 'roleuser', ['login'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roleuser_login'), table_name='roleuser')
    op.create_index('ix_roleuser_login', 'roleuser', ['login'], unique=False)
    # ### end Alembic commands ###
