"""delete TRASH UNIQUE

Revision ID: 1b86c6343e82
Revises: 6338e2dd1f62
Create Date: 2021-12-22 02:03:07.724886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b86c6343e82'
down_revision = '6338e2dd1f62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_skillhero_namehero', table_name='skillhero')
    op.create_index(op.f('ix_skillhero_namehero'), 'skillhero', ['namehero'], unique=False)
    op.drop_index('ix_skillhero_skill', table_name='skillhero')
    op.create_index(op.f('ix_skillhero_skill'), 'skillhero', ['skill'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skillhero_skill'), table_name='skillhero')
    op.create_index('ix_skillhero_skill', 'skillhero', ['skill'], unique=False)
    op.drop_index(op.f('ix_skillhero_namehero'), table_name='skillhero')
    op.create_index('ix_skillhero_namehero', 'skillhero', ['namehero'], unique=False)
    # ### end Alembic commands ###
