"""dangeoun master

Revision ID: 3be0d4d09c09
Revises: 784fc5e4dc88
Create Date: 2021-12-22 20:32:28.375686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3be0d4d09c09'
down_revision = '784fc5e4dc88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('dungeonmaster', sa.String(), nullable=False))
    op.create_index(op.f('ix_company_dungeonmaster'), 'company', ['dungeonmaster'], unique=False)
    op.create_foreign_key(None, 'company', 'customers', ['dungeonmaster'], ['login'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.drop_index(op.f('ix_company_dungeonmaster'), table_name='company')
    op.drop_column('company', 'dungeonmaster')
    # ### end Alembic commands ###
