"""relation v2

Revision ID: 4ede14c7e19e
Revises: b6ab7127d622
Create Date: 2021-12-22 01:52:53.706762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ede14c7e19e'
down_revision = 'b6ab7127d622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('customers_hero_user_fkey', 'customers', type_='foreignkey')
    op.drop_column('customers', 'hero_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('hero_user', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('customers_hero_user_fkey', 'customers', 'hero', ['hero_user'], ['namehero'])
    # ### end Alembic commands ###
