"""delete TRASH UNIQUE v2

Revision ID: 5d5e5e537a63
Revises: 1b86c6343e82
Create Date: 2021-12-22 02:10:16.084131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d5e5e537a63'
down_revision = '1b86c6343e82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customerscompany_login', table_name='customerscompany')
    op.create_index(op.f('ix_customerscompany_login'), 'customerscompany', ['login'], unique=False)
    op.drop_index('ix_customersplay_login', table_name='customersplay')
    op.create_index(op.f('ix_customersplay_login'), 'customersplay', ['login'], unique=False)
    op.drop_index('ix_news_login', table_name='news')
    op.create_index(op.f('ix_news_login'), 'news', ['login'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_login'), table_name='news')
    op.create_index('ix_news_login', 'news', ['login'], unique=False)
    op.drop_index(op.f('ix_customersplay_login'), table_name='customersplay')
    op.create_index('ix_customersplay_login', 'customersplay', ['login'], unique=False)
    op.drop_index(op.f('ix_customerscompany_login'), table_name='customerscompany')
    op.create_index('ix_customerscompany_login', 'customerscompany', ['login'], unique=False)
    # ### end Alembic commands ###
