"""comeback and try fix

Revision ID: 6338e2dd1f62
Revises: 4ede14c7e19e
Create Date: 2021-12-22 01:58:25.126409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6338e2dd1f62'
down_revision = '4ede14c7e19e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hero', sa.Column('login', sa.String(), nullable=False))
    op.create_index(op.f('ix_hero_login'), 'hero', ['login'], unique=False)
    op.create_foreign_key(None, 'hero', 'customers', ['login'], ['login'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hero', type_='foreignkey')
    op.drop_index(op.f('ix_hero_login'), table_name='hero')
    op.drop_column('hero', 'login')
    # ### end Alembic commands ###
