"""autodate

Revision ID: 784fc5e4dc88
Revises: 5d5e5e537a63
Create Date: 2021-12-22 17:05:39.800893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '784fc5e4dc88'
down_revision = '5d5e5e537a63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'datet',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'datet',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
