"""relation

Revision ID: b6ab7127d622
Revises: c686cbe91f58
Create Date: 2021-12-22 01:29:28.060433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6ab7127d622'
down_revision = 'c686cbe91f58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('hero_user', sa.String(), nullable=True))
    op.create_foreign_key(None, 'customers', 'hero', ['hero_user'], ['namehero'])
    op.drop_index('ix_hero_login', table_name='hero')
    op.drop_constraint('hero_login_fkey', 'hero', type_='foreignkey')
    op.drop_constraint('hero_namehero_fkey', 'hero', type_='foreignkey')
    op.drop_column('hero', 'login')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hero', sa.Column('login', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('hero_namehero_fkey', 'hero', 'hero', ['namehero'], ['namehero'])
    op.create_foreign_key('hero_login_fkey', 'hero', 'customers', ['login'], ['login'])
    op.create_index('ix_hero_login', 'hero', ['login'], unique=False)
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'hero_user')
    # ### end Alembic commands ###
