"""test2

Revision ID: b92866b3f64d
Revises: ad26b741b8c4
Create Date: 2021-12-23 12:38:56.018854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b92866b3f64d'
down_revision = 'ad26b741b8c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'dungeonmaster',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'dungeonmaster',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
