"""составной ключ hero_

Revision ID: c686cbe91f58
Revises: f9e6342f8f41
Create Date: 2021-12-22 01:07:39.995111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c686cbe91f58'
down_revision = 'f9e6342f8f41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'hero', 'hero', ['namehero'], ['namehero'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hero', type_='foreignkey')
    # ### end Alembic commands ###
